INSERT INTO
    exercise_types (exercise_type)
VALUES
    ('Ab Roller'),
    ('Arm Circles'),
    ('Back Extension'),
    ('Back Squat'),
    ('Bear Crawl'),
    ('Bench Dip'),
    ('Bench Press'),
    ('Bent Over Row'),
    ('Bicycle Crunch'),
    ('Bird Dog'),
    ('Bodyweight Squat'),
    ('Box Jump'),
    ('Bulgarian Split Squat'),
    ('Burpee'),
    ('Calf Raise'),
    ('Chest Fly'),
    ('Chest Press'),
    ('Chin-Up'),
    ('Clean and Jerk'),
    ('Close-Grip Bench Press'),
    ('Clapping Push-Up'),
    ('Curl-Up'),
    ('Deadlift'),
    ('Decline Push-Up'),
    ('Diamond Push-Up'),
    ('Dips'),
    ('Dumbbell Curl'),
    ('Dumbbell Fly'),
    ('Dumbbell Lunge'),
    ('Dumbbell Press'),
    ('Dumbbell Row'),
    ('Dumbbell Shrug'),
    ('Dumbbell Squat'),
    ('Dumbbell Step-Up'),
    ('Face Pull'),
    ('Front Squat'),
    ('Glute Bridge'),
    ('Good Morning'),
    ('Hanging Leg Raise'),
    ('Handstand Push-Up'),
    ('High Knees'),
    ('Hip Thrust'),
    ('Hollow Body Hold'),
    ('Inchworm'),
    ('Incline Bench Press'),
    ('Incline Push-Up'),
    ('Jump Rope'),
    ('Jump Squat'),
    ('Kettlebell Swing'),
    ('Kneeling Push-Up'),
    ('Lat Pulldown'),
    ('Leg Curl'),
    ('Leg Extension'),
    ('Leg Press'),
    ('Lunge'),
    ('Mountain Climber'),
    ('Muscle-Up'),
    ('One-Arm Push-Up'),
    ('Overhead Press'),
    ('Pistol Squat'),
    ('Plank'),
    ('Power Clean'),
    ('Pull-Up'),
    ('Push Press'),
    ('Push-Up'),
    ('Rear Delt Fly'),
    ('Renegade Row'),
    ('Reverse Crunch'),
    ('Russian Twist'),
    ('Scissor Kick'),
    ('Shoulder Press'),
    ('Side Plank'),
    ('Single-Leg Deadlift'),
    ('Sit-Up'),
    ('Skipping'),
    ('Sled Push'),
    ('Sled Pull'),
    ('Split Squat'),
    ('Squat'),
    ('Squat Jump'),
    ('Standing Calf Raise'),
    ('Standing Press'),
    ('Step-Up'),
    ('Straight-Leg Deadlift'),
    ('Superman'),
    ('T-Bar Row'),
    ('Thruster'),
    ('Toes to Bar'),
    ('Tricep Dip'),
    ('Tricep Extension'),
    ('Tricep Pushdown'),
    ('Tuck Jump'),
    ('Turkish Get-Up'),
    ('Upright Row'),
    ('V-Up'),
    ('Wall Sit'),
    ('Walking Lunge'),
    ('Wide-Grip Bench Press'),
    ('Wide-Grip Pull-Up'),
    ('Windshield Wipers');