INSERT INTO exercise_types (exercise_type, colour)
VALUES
    ('Ab Roller', '#FF5733'),
    ('Arm Circles', '#33FF57'),
    ('Back Extension', '#3357FF'),
    ('Back Squat', '#FF33A6'),
    ('Bear Crawl', '#A633FF'),
    ('Bench Dip', '#FF9633'),
    ('Bench Press', '#33FFD5'),
    ('Bent Over Row', '#FFA633'),
    ('Bicep Curl', '#33A6FF'),
    ('Bird Dog', '#FF3357'),
    ('Bodyweight Squat', '#57FF33'),
    ('Box Jump', '#A6FF33'),
    ('Bulgarian Split Squat', '#FF5733'),
    ('Burpee', '#33FFA6'),
    ('Calf Raise', '#FF33FF'),
    ('Chest Fly', '#5733FF'),
    ('Chest Press', '#33FF57'),
    ('Chin-Up', '#33A6FF'),
    ('Clean and Jerk', '#FF33A6'),
    ('Close-Grip Bench Press', '#33FFD5'),
    ('Clapping Push-Up', '#FFA633'),
    ('Curl-Up', '#33A6FF'),
    ('Deadlift', '#FF3357'),
    ('Decline Push-Up', '#57FF33'),
    ('Diamond Push-Up', '#A6FF33'),
    ('Dips', '#FF5733'),
    ('Dumbbell Curl', '#33FFA6'),
    ('Dumbbell Fly', '#FF33FF'),
    ('Dumbbell Lunge', '#5733FF'),
    ('Dumbbell Press', '#33FF57'),
    ('Dumbbell Row', '#33A6FF'),
    ('Dumbbell Shrug', '#FF33A6'),
    ('Dumbbell Squat', '#33FFD5'),
    ('Dumbbell Step-Up', '#FFA633'),
    ('Face Pull', '#33A6FF'),
    ('Front Squat', '#FF3357'),
    ('Glute Bridge', '#57FF33'),
    ('Good Morning', '#A6FF33'),
    ('Hanging Leg Raise', '#FF5733'),
    ('Handstand Push-Up', '#33FFA6'),
    ('High Knees', '#FF33FF'),
    ('Hip Thrust', '#5733FF'),
    ('Hollow Body Hold', '#33FF57'),
    ('Inchworm', '#33A6FF'),
    ('Incline Bench Press', '#FF33A6'),
    ('Incline Push-Up', '#33FFD5'),
    ('Jump Rope', '#FFA633'),
    ('Jump Squat', '#33A6FF'),
    ('Kettlebell Swing', '#FF3357'),
    ('Kneeling Push-Up', '#57FF33'),
    ('Lat Pulldown', '#A6FF33'),
    ('Leg Curl', '#FF5733'),
    ('Leg Extension', '#33FFA6'),
    ('Leg Press', '#FF33FF'),
    ('Lunge', '#5733FF'),
    ('Mountain Climber', '#33FF57'),
    ('Muscle-Up', '#33A6FF'),
    ('One-Arm Push-Up', '#FF33A6'),
    ('Overhead Press', '#33FFD5'),
    ('Pistol Squat', '#FFA633'),
    ('Plank', '#33A6FF'),
    ('Power Clean', '#FF3357'),
    ('Pull-Up', '#57FF33'),
    ('Push Press', '#A6FF33'),
    ('Push-Up', '#FF5733'),
    ('Rear Delt Fly', '#33FFA6'),
    ('Renegade Row', '#FF33FF'),
    ('Reverse Crunch', '#5733FF'),
    ('Russian Twist', '#33FF57'),
    ('Scissor Kick', '#33A6FF'),
    ('Shoulder Press', '#FF33A6'),
    ('Side Plank', '#33FFD5'),
    ('Single-Leg Deadlift', '#FFA633'),
    ('Sit-Up', '#33A6FF'),
    ('Skipping', '#FF3357'),
    ('Sled Push', '#57FF33'),
    ('Sled Pull', '#A6FF33'),
    ('Split Squat', '#FF5733'),
    ('Squat', '#33FFA6'),
    ('Squat Jump', '#FF33FF'),
    ('Standing Calf Raise', '#5733FF'),
    ('Standing Press', '#33FF57'),
    ('Step-Up', '#33A6FF'),
    ('Straight-Leg Deadlift', '#FF33A6'),
    ('Superman', '#33FFD5'),
    ('T-Bar Row', '#FFA633'),
    ('Thruster', '#33A6FF'),
    ('Toes to Bar', '#FF3357'),
    ('Tricep Dip', '#57FF33'),
    ('Tricep Extension', '#A6FF33'),
    ('Tricep Pushdown', '#FF5733'),
    ('Tuck Jump', '#33FFA6'),
    ('Turkish Get-Up', '#FF33FF'),
    ('Upright Row', '#5733FF'),
    ('V-Up', '#33FF57'),
    ('Wall Sit', '#33A6FF'),
    ('Walking Lunge', '#FF33A6'),
    ('Wide-Grip Bench Press', '#33FFD5'),
    ('Wide-Grip Pull-Up', '#FFA633'),
    ('Windshield Wipers', '#33A6FF');
